agents/urls.py
from django.urls import path
from . import views


app_name = 'agents'

urlpatterns = [
    path('', views.agents_list , name='agent_list'),
   
]
 

projecthotel/urls.py
from django.contrib import admin
from django.urls import path , include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('property/', include('property.urls', namespace= 'property')),
    path('agents/', include('agents.urls', namespace= 'agents'))
]

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

property/urls.py
from django.urls import path
from . import views


app_name = 'property'

urlpatterns = [
    path('', views.property_list , name='property_list'),
    path('<int:id>', views. property_detail , name='property_detail'),
]
 

agents/models.py
from django.db import models

# Create your models here.
class Agent(models.Model):
    name = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to='agents/')

    def __str__(self):
         return self.name

property/models.py
from django.db import models

# Create your models here.

property_type = ( 
    ('S' , "sale"),
    ('R' , "rent")

)
class property(models.Model):
    name = models.CharField(max_length=50)
    property_type = models.CharField(choices=property_type , max_length=10)
    price = models.PositiveIntegerField()
    catagory = models.ForeignKey('catagory' ,null=True, on_delete=models.SET_NULL)
    area = models.DecimalField(decimal_places=2 , max_digits=8)
    beds_number = models.PositiveIntegerField() 
    baths_number = models.PositiveIntegerField()
    garages_number = models.PositiveIntegerField()
    images = models.ImageField(upload_to='property/' , null=True)
    def __str__(self):
        return self.name
    class meta:
        verbose_name = 'property'
        verbose_name_plural = 'properties'



class catagory(models.Model):
    catagory_name = models.CharField(max_length=30)

    def __str__(self):
        return self.catagory_name
    class meta:
        verbose_name = 'catagory'
        verbose_name_plural = 'catagories' 




    


class Reserve(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    notes = models.TextField()

    def __str__(self):
        return self.name

property/forms.py
from django import forms
from django.db.models import fields
from .models import Reserve


class ReserveFrom(forms.ModelForm):
    class Meta :
        model = Reserve
        fields = '__all__'

agents/views.py
from re import template
from django.shortcuts import render
from .models import Agent
# Create your views here.

def agents_list(request):
    agent_list = Agent.objects.all()
    template = 'agents/agents.html'
    context = {
     'agent_list' : agent_list
    }
    return render(request , template , context)
    

property/views.py
from django.shortcuts import render
from .forms import ReserveFrom

# Create your views here.
from .models import property , catagory

def property_list(request):
    property_list = property.objects.all() 
    template = 'property/list.html' 
    context = {
        'property_list' : property_list
    }
    
    return render(request , template , context)

def property_detail(request , id):
    property_detail = property.objects.get( id = id )
    template = 'property/detail.html'
    

    if request.method == 'POST':
        reserve_form = ReserveFrom(request.POST)
        if reserve_form.is_valid():
            reserve_form.save()

    else:
        reserve_form = ReserveFrom()


    context = {
        'property_detail' : property_detail ,
        'reserve_form' : reserve_form 
    }
    
    return render(request , template , context)

agents/templates/agents/agents.html
{% extends 'base.html' %}

{% block body %}


  <section class="probootstrap-slider flexslider2 page-inner">
    <div class="overlay"></div>
    <div class="probootstrap-wrap-banner">
      <div class="container">
        <div class="row">
          <div class="col-md-8">

            <div class="page-title probootstrap-animate">
              <div class="probootstrap-breadcrumbs">
                <a href="#">Home</a><span>Agents</span>
              </div>
              <h1>Agents</h1>
            </div>

          </div>
        </div>
      </div>
    </div>
    <ul class="slides">
      <li style="background-image: url(img/slider_1.jpg);"></li>
      <li style="background-image: url(img/slider_4.jpg);"></li>
      <li style="background-image: url(img/slider_2.jpg);"></li>
    </ul>
  </section>
  <!-- END: slider  -->
  
  <section class="probootstrap-section probootstrap-section-lighter">
    <div class="container">
      <div class="row heading">
        <h2 class="mt0 mb50 text-center">کارکنان شرکت</h2>
      </div>
      <div class="row">

        {% for agent in agent_list %} 

         <div class="col-md-3 col-sm-6">
          <div class="probootstrap-card probootstrap-person text-left">
            <div class="probootstrap-card-media">
              <img src="{{agent.image.url}}" class="img-responsive" alt="Free HTML5 Template by uicookies.com">
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading mb0">{{agent.name}}</h2>
              <p><small>{{agent.title}}</small></p>
              
            </div>
          </div>
         </div>
         
        {% endfor %}


      </div>
    </div>
  </section>



{% endblock body %}

property/templates/property/detail.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

  <section class="probootstrap-slider flexslider2 page-inner">
    <div class="overlay"></div>
    <div class="probootstrap-wrap-banner">
      <div class="container">
        <div class="row">
          <div class="col-md-8">

            <div class="page-title probootstrap-animate">
              <div class="probootstrap-breadcrumbs">
                <a href="#">Home</a><span><a href="{% url 'property:property_list' %}">Properties</a></span>{{property_detail}}
              </div>
              <h1>Properties</h1>
            </div>


          </div>
        </div>
      </div>
    </div>
    <ul class="slides">
      <li style="background-image: url(img/slider_1.jpg);"></li>
      <li style="background-image: url(img/slider_4.jpg);"></li>
      <li style="background-image: url(img/slider_2.jpg);"></li>
    </ul>
  </section>
  <!-- END: slider  -->

  <section class="probootstrap-section">
    <div class="container">
      <div class="row heading">
      
      </div>
      <div class="row">
        <div class="col-md-12">
          <p><img src="{{property_detail.image.url}}" class="img-responsive" alt="house pic"></p>
          <a href="https://icedrive.net/1/02aIfTIj8z"> کلیک برای دیدن خانه ها</a>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <h2>اطلاعات مسکن</h2>
          <p>فروش یا اجاره{{property_detail.property_type}} برای خریدs </p>
          <p>متراژ {{property_detail.area}}</p>
          <p>تعداد اتاق{{property_detail.beds_number}}</p>
          <p>تعداد سرویس بهداشتی{{property_detail.baths_number}}</p>
          <p>تعداد جای پارک{{property_detail.garages_number}}</p>

        </div>

      </div>
    </div>
  </section>

  <section class="probootstrap-section">
    <div class="container">
      <div class="row heading">
      
      </div>

      </div>
      <div class="row">
        <div class="col-md-12">
          <center>رزو کردن فرست خرید یا اجاره</center>
          <form action="" method="POST">
            {% csrf_token %}
          {{reserve_form}}
          <button type = "submit" class="btn btn-primary">بارگذاری</button>

        </div>

      </div>
    </div>
  </section>




{% endblock body %}
 

property/templates/property/list.html
{% extends 'base.html'%}

{% block body %}


  <section class="probootstrap-slider flexslider2 page-inner">
    <div class="overlay"></div>
    <div class="probootstrap-wrap-banner">
      <div class="container">
        <div class="row">
          <div class="col-md-8">

            <div class="page-title probootstrap-animate">
              <div class="probootstrap-breadcrumbs">
                <a href="#">Home</a><span>Properties</span>
              </div>
              <h1>وبسایت پروژه لایتک شریف امیررضا دادگر</h1>
            </div>

          </div>
        </div>
      </div>
    </div>
    <ul class="slides">
      <li style="background-image: url(img/slider_1.jpg);"></li>
      <li style="background-image: url(img/slider_4.jpg);"></li>
      <li style="background-image: url(img/slider_2.jpg);"></li>
    </ul>
  </section>
  <!-- END: slider  -->

  <section class="probootstrap-section probootstrap-section-lighter">
    <div class="container">
      <div class="row">
        {% for property in property_list %}
        
        <div class="col-md-4 col-sm-6">
          <div class="probootstrap-card probootstrap-listing">
            <div class="probootstrap-card-media">
              <img src="{{property.image.url}}" class="img-responsive" alt="pic of the place">
              
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading"><a href="{% url 'property:property_detail' property.id %}">{{property}}</a></h2>
              <div class="probootstrap-listing-location">
                <i class="icon-location2"></i> <span>محل خرید در تهران  </span>
              </div>
              <div class="probootstrap-listing-category for-sale"><span>for sale</span></div>
              <div class="probootstrap-listing-price"><strong>$ {{property.price}}</strong> / month</div>
            </div>
            <div class="probootstrap-card-extra">
              <ul>
                <li>
                  Area
                  <span>{{property.area}}</span>
                </li>
                <li>
                  Beds
                  <span>{{property.beds_number}}</span>
                </li>
                <li>
                  Baths
                  <span>{{property.baths_number}}</span>
                </li>
                <li>
                  Garages
                  <span>{{property.garages_number}}</span>
                </li>
              </ul>
            </div>
          </div>
          <!-- END listing -->
        </div>
        {% endfor %}

    </div>
  </section>

  





  {% endblock body %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>uiCookies:Haus &mdash; Free Bootstrap Theme, Free Responsive Bootstrap Website Template</title>
    <meta name="description" content="Free Bootstrap Theme by uicookies.com">
    <meta name="keywords" content="free website templates, free bootstrap themes, free template, free bootstrap, free website template">
    
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles-merged.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <!--[if lt IE 9]>
      <script src="js/vendor/html5shiv.min.js"></script>
      <script src="js/vendor/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

  <!-- START: header -->
  
  <div class="probootstrap-loader"></div>

  <header role="banner" class="probootstrap-header">
    <div class="container">
        <a href="index.html" class="probootstrap-logo">Haus<span>.</span></a>
        
        <a href="#" class="probootstrap-burger-menu visible-xs" ><i>Menu</i></a>
        <div class="mobile-menu-overlay"></div>

        <nav role="navigation" class="probootstrap-nav hidden-xs">
          <ul class="probootstrap-main-nav">
            <li class=""><a href="/">Home</a></li>
            <li {% if property_list %} class="active"{% endif %}><a href="{% url 'property:property_list' %}">Properties</a></li>
            <li {% if agent_list %} class="active"{% endif %}><a href="{% url 'agents:agent_list' %}">Agents</a></li>
           
          </ul>
          <div class="extra-text visible-xs"> 
            <a href="#" class="probootstrap-burger-menu"><i>Menu</i></a>
            <h5>Address</h5>
            <p>198 West 21th Street, Suite 721 New York NY 10016</p>
            <h5>Connect</h5>
            <ul class="social-buttons">
              <li><a href="#"><i class="icon-twitter"></i></a></li>
              <li><a href="#"><i class="icon-facebook2"></i></a></li>
              <li><a href="#"><i class="icon-instagram2"></i></a></li>
            </ul>
          </div>
        </nav>
    </div>
  </header>



  {% block body %}

  {% endblock body %}

  <footer class="probootstrap-footer probootstrap-bg" style="background-image: url(img/slider_3.jpg)">
    <div class="container">
      <div class="row mb60">
        <div class="col-md-3">
          <div class="probootstrap-footer-widget">
            <h4 class="heading">About Haus.</h4>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. </p>
            <p><a href="#">Read more...</a></p>
          </div> 
        </div>
        <div class="col-md-3">
          <div class="probootstrap-footer-widget probootstrap-link-wrap">
            <h4 class="heading">Quick Links</h4>
            <ul class="stack-link">
              <li><a href="#">Property Listing</a></li>
              <li><a href="#">Rent Properties</a></li>
              <li><a href="#">Sell Properties</a></li>
              <li><a href="#">Agents</a></li>
              <li><a href="#">Testimonial</a></li>
            </ul>
          </div>
        </div>
        <div class="col-md-3">
          <div class="probootstrap-footer-widget">
            <h4 class="heading">Popular Cities</h4>
            <ul class="stack-link">
              <li><a href="#">New York <small>(320 properties)</small></a></li>
              <li><a href="#">San Francisco <small>(294 properties)</small></a></li>
              <li><a href="#">Brooklyn <small>(300 properties)</small></a></li>
              <li><a href="#">Chicago <small>(268 properties)</small></a></li>
              <li><a href="#">Los Angeles <small>(342 properties)</small></a></li>
            </ul>
          </div> 
        </div>
        <div class="col-md-3">
          <div class="probootstrap-footer-widget probootstrap-link-wrap">
            <h4 class="heading">Subscribe</h4>
            <p>Far far away behind the word mountains far from.</p>
            <form action="#">
              <div class="form-field">
                <input type="text" class="form-control" placeholder="Enter your email">
                <button class="btn btn-subscribe">Send</button>
              </div>
            </form>
          </div>
        </div>
      </div>
      <div class="row copyright">
        <div class="col-md-6">
          <div class="probootstrap-footer-widget">
            <p>&copy; 2017 <a href="https://uicookies.com/">uiCookies:Haus</a>. Designed by <a href="https://uicookies.com/">uicookies.com</a> <br> Demo Photos from <a href="https://pixabay.com/">Pixabay</a> &amp; <a href="https://unsplash.com/">Unsplash</a></p>
          </div>
        </div>
        <div class="col-md-6">
          <div class="probootstrap-footer-widget right">
            <ul class="probootstrap-footer-social">
              <li><a href="#"><i class="icon-twitter"></i></a></li>
              <li><a href="#"><i class="icon-facebook"></i></a></li>
              <li><a href="#"><i class="icon-instagram2"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </footer>

  <div class="gototop js-top">
    <a href="#" class="js-gotop"><i class="icon-chevron-thin-up"></i></a>
  </div>
  

  <script src="{% static 'js/scripts.min.js'%}"></script>
  <script src="{% static 'js/main.min.js'%}"></script>
  <script src="{% static 'js/custom.js'%}"></script>

  </body>
</html>